services:
  - type: web
    name: dontbedumb-backend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SEARXNG_API_URL
        value: https://searx.be
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: dontbedumb
    env: node
    buildCommand: cd ui && yarn install && yarn build && cp -r .next/standalone ./standalone && cp -r .next/static ./standalone/.next/static && cp next.config.js ./standalone && cp package.json ./standalone
    startCommand: cd ui/standalone && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://dontbedumb-backend.onrender.com/api
      - key: NEXT_PUBLIC_WS_URL
        value: wss://dontbedumb-backend.onrender.com
      - key: PORT
        value: 3000

envVarGroups:
  - name: perplexica-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false