services:
  - type: web
    name: dontbedumb-backend
    env: node
    buildCommand: yarn install && yarn build && cp -r dist .
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SEARXNG_API_URL
        value: https://searx.be
      - key: OPENAI_API_KEY
        sync: false

envVarGroups:
  - name: perplexica-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false